// Expo config plugin: wire android/app/build.gradle to read release signing
// credentials from a `keystore.properties` file at the android/ root.
//
// At `expo prebuild --platform android`, this plugin patches the generated
// `android/app/build.gradle` to:
//   1. Load `android/keystore.properties` (git-ignored, written by
//      scripts/android-release.sh from FAWN_ANDROID_* env vars).
//   2. Define a `signingConfigs.release` block backed by those properties.
//   3. Point `buildTypes.release.signingConfig` at that release config
//      (replacing the default Expo template which signs release with the
//      debug keystore).
//
// The patch is idempotent: a marker comment prevents double-injection if the
// plugin runs more than once against the same file (e.g. after a partial
// prebuild). If `keystore.properties` is absent at build time the release
// config falls back to no-op so debug builds still work.
//
// Why a config plugin (not a manual patch): `mobile/android/` is git-ignored
// and regenerated by `expo prebuild`. Any hand-edit to the generated file is
// lost. A config plugin runs every prebuild, so the wiring is repeatable.

const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = '// fawn:release-signing-injected';

const KEYSTORE_LOADER = `
${MARKER}
def fawnKeystorePropsFile = rootProject.file("keystore.properties")
def fawnKeystoreProps = new Properties()
if (fawnKeystorePropsFile.exists()) {
    fawnKeystorePropsFile.withInputStream { fawnKeystoreProps.load(it) }
}
`.trim();

const SIGNING_CONFIG = `
        release {
            if (fawnKeystorePropsFile.exists()) {
                storeFile file(fawnKeystoreProps['storeFile'])
                storePassword fawnKeystoreProps['storePassword']
                keyAlias fawnKeystoreProps['keyAlias']
                keyPassword fawnKeystoreProps['keyPassword']
            }
        }
`;

function injectKeystoreLoader(contents) {
  if (contents.includes(MARKER)) return contents;
  // Insert just before the top-level `android {` block.
  const androidBlockIdx = contents.search(/^android\s*\{/m);
  if (androidBlockIdx === -1) {
    throw new Error(
      "[withAndroidReleaseSigning] could not find top-level 'android {' block in app/build.gradle",
    );
  }
  return (
    contents.slice(0, androidBlockIdx) +
    KEYSTORE_LOADER +
    '\n\n' +
    contents.slice(androidBlockIdx)
  );
}

function injectReleaseSigningConfig(contents) {
  // Replace the entire signingConfigs { ... } block so we own it.
  // The Expo template emits a `signingConfigs { debug { ... } }` block;
  // we keep `debug` and append `release`.
  const signingConfigsRe =
    /signingConfigs\s*\{\s*([\s\S]*?)\n\s{4}\}\n/m;
  const match = contents.match(signingConfigsRe);
  if (!match) {
    throw new Error(
      "[withAndroidReleaseSigning] could not find 'signingConfigs {' block in app/build.gradle",
    );
  }
  const inner = match[1];
  if (/\brelease\s*\{/.test(inner)) {
    // Already has a release entry — leave it alone, the user (or a later
    // template change) owns it.
    return contents;
  }
  const replacement = `signingConfigs {\n${inner}\n${SIGNING_CONFIG}    }\n`;
  return contents.replace(signingConfigsRe, replacement);
}

function pointReleaseBuildTypeAtReleaseSigningConfig(contents) {
  // Expo's default sets `signingConfig signingConfigs.debug` inside
  // `buildTypes { release { ... } }`. Swap it to `signingConfigs.release`.
  // We match within the release { ... } block to avoid touching debug.
  const releaseBuildTypeRe =
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?signingConfig\s+)signingConfigs\.debug/m;
  if (!releaseBuildTypeRe.test(contents)) {
    // Either already swapped, or the template changed. If a release signingConfig
    // is not set at all, append one inside the release block.
    const releaseBlockRe = /(buildTypes\s*\{[\s\S]*?release\s*\{)/m;
    if (
      releaseBlockRe.test(contents) &&
      !/release\s*\{[\s\S]*?signingConfig\s+signingConfigs\.release/m.test(
        contents,
      )
    ) {
      return contents.replace(
        releaseBlockRe,
        '$1\n            signingConfig signingConfigs.release',
      );
    }
    return contents;
  }
  return contents.replace(releaseBuildTypeRe, '$1signingConfigs.release');
}

const withAndroidReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        '[withAndroidReleaseSigning] expected android/app/build.gradle to be Groovy',
      );
    }
    let contents = cfg.modResults.contents;
    contents = injectKeystoreLoader(contents);
    contents = injectReleaseSigningConfig(contents);
    contents = pointReleaseBuildTypeAtReleaseSigningConfig(contents);
    cfg.modResults.contents = contents;
    return cfg;
  });

module.exports = withAndroidReleaseSigning;
